### ISSUE TITLE
Should the player have a hunger/food bar?

### ISSUE THREAD

**Issue by VaporeonMega** [fis-programming-club/2018#43]

**Comment by Frederik-Hollis** [comment]
NOooooo

**Comment by TimothyGorst** [comment]
no the way I'm thinking of the game is that each level is a speedrun. This can help with having music that fits. I am creating an issue about general level design

**Comment by Frederik-Hollis** [comment]
wait what is a speedrun?

**Comment by Frederik-Hollis** [comment]
NO
